name: Release
on:
  workflow_dispatch:
  
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
      - name: Git config
        run: |
          git config user.name autograding-release-bot
          git config user.email autograding-release-bot+education@github.com
      - name: Run build and commit to releases/v1
        run: |
          git checkout -b releases/v1
          npm install --silent
          npm run build
          git add dist/
          git commit -m "Release v1"
          git push -f origin releases/v1
      - name: Tag and push v1
        run: |
          git checkout releases/v1
          git tag -f v1
          git push origin v1 --force
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: v1
          allowUpdates: true
